### ISSUE TITLE
Syntax Coloring for Manual Install Commands

### ISSUE THREAD

**Issue by sbdchd** [cheddar-lang/cheddar-lang.github.io#11]
In the manual install section, the syntax highlighting makes it difficult to see the install commands.

<img width="466" alt="screenshot 2016-08-07 11 12 12" src="https://cloud.githubusercontent.com/assets/7340772/17463270/43243f84-5c90-11e6-8bf1-649290e08ead.png">

**Comment by RikerW** [comment]
I'll fix this. BTW, who are you on PPCG?

**Comment by vihanb** [comment]
Fixed in cd482dd973026e95623f103be826a7a5e6a93803

**Comment by sbdchd** [comment]
@RikerW I am just an occasional observer of PPCG.
